### ISSUE TITLE
ASP Core embedded sample

### ISSUE THREAD

**Issue by weedkiller** [metabase/embedding-reference-apps#55]
Hello, can you add some help on embedding inside ASP Core or Orchard core web apps

**Comment by flamber** [comment]
Hi @weedkiller 
I don't think we have any developers who have coded in ASP Core or Orchard, but you're more than welcome to create a PR.
Since Metabase uses the JWT standard for embedding, then you can likely find examples on the internet by searching:
`asp core jwt example`
Here's the first result: https://jasonwatmore.com/post/2019/10/11/aspnet-core-3-jwt-authentication-tutorial-with-example-api

**Comment by weedkiller** [comment]
besides the token the actual integration information is lacking.
